export enum UserRole {
  ADMIN = 'ADMIN',
  DEVELOPER = 'DEVELOPER',
}

export enum ProjectStatus {
  ATIVO = 'ATIVO',
  PAUSADO = 'PAUSADO',
  CONCLUIDO = 'CONCLUIDO',
  CANCELADO = 'CANCELADO',
  NA_FILA = 'NA_FILA',
}

export enum TaskStatus {
  BACKLOG = 'BACKLOG',
  PLANEJADA = 'PLANEJADA',
  BLOQUEADA = 'BLOQUEADA',
  EM_DESENVOLVIMENTO = 'EM_DESENVOLVIMENTO',
  EM_REVISAO = 'EM_REVISAO',
  HOMOLOGACAO = 'HOMOLOGACAO',
  CONCLUIDA = 'CONCLUIDA',
  CANCELADA = 'CANCELADA',
}

export enum DependencyType {
  BLOCKS = 'BLOCKS',
  BLOCKED_BY = 'BLOCKED_BY',
  RELATED = 'RELATED',
}

export enum TimeLogSource {
  TIMER = 'TIMER',
  MANUAL = 'MANUAL',
}

export enum ModuleStatus {
  INICIADO = 'INICIADO',
  EM_PROCESSO = 'EM_PROCESSO',
  CONCLUIDO = 'CONCLUIDO',
}

export enum NotificationType {
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  TASK_UPDATED = 'TASK_UPDATED',
  TASK_BLOCKED = 'TASK_BLOCKED',
  TASK_COMPLETED = 'TASK_COMPLETED',
  TASK_OVERDUE = 'TASK_OVERDUE',
  COMMENT_ADDED = 'COMMENT_ADDED',
  DEPENDENCY_RESOLVED = 'DEPENDENCY_RESOLVED',
  PROJECT_UPDATED = 'PROJECT_UPDATED',
}

export enum AuditEntityType {
  TASK = 'TASK',
  PROJECT = 'PROJECT',
  MODULE = 'MODULE',
  EPIC = 'EPIC',
  USER = 'USER',
}

export enum AuditAction {
  CREATED = 'CREATED',
  UPDATED = 'UPDATED',
  DELETED = 'DELETED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  ASSIGNED = 'ASSIGNED',
  COMMENTED = 'COMMENTED',
  TIME_LOGGED = 'TIME_LOGGED',
}
